/**
 * Linux Hyprland install for dottie-talk keys.
 * Off until keys.enabled. Binds only apply while HTTP writes the runtime flag.
 */

import { execFile } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { PORTS } from './ports.js';
import { loadConfig, setKeysEnabled } from './config.js';
import { dictate, keysFlagPath, keysStatus, removeKeysFlag, speakSelection, stopSpeak, writeKeysFlag } from './keys.js';

const execFileAsync = promisify(execFile);
const MARKER = '# dottie-talk-keys';
const BEGIN = '-- dottie-talk-keys: begin';
const END = '-- dottie-talk-keys: end';
const CLI = fileURLToPath(new URL('./cli.js', import.meta.url));

export function hyprDir() {
  return process.env.DOTTIE_TALK_HYPR_DIR || path.join(os.homedir(), '.config', 'hypr');
}

export function userBinDir() {
  return process.env.DOTTIE_TALK_USER_BIN || path.join(os.homedir(), '.local', 'bin');
}

export function wrapperPaths() {
  const dir = userBinDir();
  return {
    speak: path.join(dir, 'speak-selection'),
    stop: path.join(dir, 'speak-stop'),
    dictate: path.join(dir, 'dottie-talk-dictate'),
    dictateStart: path.join(dir, 'dottie-talk-dictate-start'),
    dictateStop: path.join(dir, 'dottie-talk-dictate-stop'),
  };
}

export function wrapperScript(action) {
  const node = process.execPath;
  return `#!/bin/sh
${MARKER}
export DOTTIE_TALK_KEYS_HOTKEY=1
export XDG_RUNTIME_DIR="\${XDG_RUNTIME_DIR:-/run/user/\$(id -u)}"
mkdir -p "\$XDG_RUNTIME_DIR/dottie-talk"
echo "\$(date -Iseconds) ${action}" >> "\$XDG_RUNTIME_DIR/dottie-talk/keys.log"
exec ${shellQuote(node)} ${shellQuote(CLI)} keys ${action} "$@"
`;
}

function shellQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function luaQuote(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

export function renderKeysLua({
  speak,
  stop,
  dictate,
  speakBin,
  stopBin,
  dictateBin,
  dictateStartBin,
  dictateStopBin,
} = {}) {
  const lines = [
    '-- generated by dottie-talk; do not edit',
    `local flag = (os.getenv("XDG_RUNTIME_DIR") or "/tmp") .. "/dottie-talk-keys.on"`,
    'local f = io.open(flag, "r")',
    'if not f then',
    '  return',
    'end',
    'f:close()',
    '',
  ];
  if (speak && speakBin) {
    lines.push(`hl.unbind(${luaQuote(speak)})`);
    lines.push(`o.bind(${luaQuote(speak)}, "Speak selection", "setsid -f " .. ${luaQuote(speakBin)})`);
  }
  if (dictate && dictateBin) {
    lines.push(`hl.unbind(${luaQuote(dictate)})`);
    lines.push(`o.bind(${luaQuote(dictate)}, "Toggle dictation", "setsid -f " .. ${luaQuote(dictateBin)})`);
  }
  if (stop && stopBin) {
    lines.push(`o.bind(${luaQuote(stop)}, "Stop speak", function()`);
    lines.push('  local runtime = os.getenv("XDG_RUNTIME_DIR") or "/tmp"');
    lines.push('  local active = io.open(runtime .. "/speak.active", "r")');
    lines.push('  if not active then');
    lines.push('    return { ok = false }');
    lines.push('  end');
    lines.push('  active:close()');
    lines.push(`  os.execute("setsid -f " .. ${luaQuote(stopBin)} .. " >/dev/null 2>&1")`);
    lines.push('end, { auto_consuming = true })');
  }
  lines.push('');
  return lines.join('\n');
}

export function keysLuaPath() {
  return path.join(hyprDir(), 'dottie-talk-keys.lua');
}

export function hyprlandPath() {
  return path.join(hyprDir(), 'hyprland.lua');
}

export function injectHyprland(src) {
  if (src.includes(BEGIN)) return src;
  const block = `${BEGIN}\npcall(require, "hypr.dottie-talk-keys")\n${END}`;
  return `${String(src).replace(/\s*$/, '')}\n\n${block}\n`;
}

export function removeHyprland(src) {
  return String(src).replace(/\n*-- dottie-talk-keys: begin[\s\S]*?-- dottie-talk-keys: end\n?/, '\n');
}

function ours(file) {
  if (!existsSync(file)) return false;
  try {
    const body = readFileSync(file, 'utf8');
    return body.includes(MARKER) || body.includes('generated by dottie-talk');
  } catch {
    return false;
  }
}

export function writeWrappers() {
  const dir = userBinDir();
  mkdirSync(dir, { recursive: true });
  const files = wrapperPaths();
  const bodies = {
    speak: wrapperScript('speak'),
    stop: wrapperScript('stop'),
    dictate: wrapperScript('dictate'),
    dictateStart: wrapperScript('dictate-start'),
    dictateStop: wrapperScript('dictate-stop'),
  };
  for (const [name, file] of Object.entries(files)) {
    if (existsSync(file) && !ours(file)) continue;
    writeFileSync(file, bodies[name]);
    chmodSync(file, 0o755);
  }
  return files;
}

export function removeWrappers() {
  for (const file of Object.values(wrapperPaths())) {
    if (ours(file)) {
      try { unlinkSync(file); } catch { /* ok */ }
    }
  }
}

export function writeKeysLua() {
  const { keys } = loadConfig();
  const bins = wrapperPaths();
  mkdirSync(hyprDir(), { recursive: true });
  const body = renderKeysLua({
    speak: keys.speak,
    stop: keys.stop,
    dictate: keys.dictate,
    speakBin: bins.speak,
    stopBin: bins.stop,
    dictateBin: bins.dictate,
    dictateStartBin: bins.dictateStart,
    dictateStopBin: bins.dictateStop,
  });
  writeFileSync(keysLuaPath(), body);
  return keysLuaPath();
}

export function injectHyprlandFile() {
  const file = hyprlandPath();
  if (!existsSync(file)) return false;
  const src = readFileSync(file, 'utf8');
  const next = injectHyprland(src);
  if (next === src) return false;
  writeFileSync(file, next);
  return true;
}

export function removeHyprlandFile() {
  const file = hyprlandPath();
  if (!existsSync(file)) return false;
  const src = readFileSync(file, 'utf8');
  if (!src.includes(BEGIN)) return false;
  writeFileSync(file, removeHyprland(src));
  return true;
}

export async function reloadHypr({ execFileFn = execFileAsync } = {}) {
  try {
    await execFileFn('hyprctl', ['reload'], { timeout: 4000, encoding: 'utf8' });
    return true;
  } catch {
    return false;
  }
}

async function armIfServerUp() {
  try {
    const res = await fetch(`http://127.0.0.1:${PORTS.TALK_HTTP_PORT}/health`, {
      signal: AbortSignal.timeout(400),
    });
    if (res.ok) writeKeysFlag();
  } catch { /* server down */ }
}

export async function enableKeys({ execFileFn = execFileAsync } = {}) {
  setKeysEnabled(true);
  writeWrappers();
  writeKeysLua();
  injectHyprlandFile();
  await armIfServerUp();
  await reloadHypr({ execFileFn });
  return keysStatus();
}

export async function disableKeys({ execFileFn = execFileAsync } = {}) {
  setKeysEnabled(false);
  removeKeysFlag();
  removeWrappers();
  try { unlinkSync(keysLuaPath()); } catch { /* ok */ }
  removeHyprlandFile();
  await reloadHypr({ execFileFn });
  return keysStatus();
}

export async function armKeys({ execFileFn = execFileAsync } = {}) {
  const { keys } = loadConfig();
  if (!keys.enabled) return { ...keysStatus(), armed: false };
  if (process.platform !== 'linux') {
    writeKeysFlag();
    return { ...keysStatus(), note: 'Linux Hyprland only. macOS: talk-keys' };
  }
  writeWrappers();
  writeKeysLua();
  injectHyprlandFile();
  writeKeysFlag();
  await reloadHypr({ execFileFn });
  return keysStatus();
}

export async function disarmKeys({ execFileFn = execFileAsync } = {}) {
  removeKeysFlag();
  if (process.platform === 'linux') await reloadHypr({ execFileFn });
  return keysStatus();
}

export async function runKeysCommand(action) {
  switch (action) {
    case 'on':
    case 'enable':
      return enableKeys();
    case 'off':
    case 'disable':
      return disableKeys();
    case 'status':
    case '':
    case undefined:
      return keysStatus();
    case 'speak':
      return speakSelection();
    case 'stop':
      return stopSpeak();
    case 'dictate':
      return dictate();
    case 'dictate-start':
      return dictate({ mode: 'start' });
    case 'dictate-stop':
      return dictate({ mode: 'stop' });
    default:
      throw new Error(`unknown keys action: ${action}`);
  }
}
